FROM node:alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install

COPY . .
RUN npm run build


FROM nginx:1.17.1-alpine


COPY --from=build /app/dist/ /usr/share/nginx/html


EXPOSE 80