services:
  web:
    build: .
    command: npm run dev
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 7
        window: 60s
    ports:
      - "8000:8000"
