version: '3.8'

services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - '5432:5432'

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    # environment:
    #   DB_USERNAME: postgres
    #   DB_PASSWORD: postgre
    #   DB_HOST_URL: db
    #   DATABASE_NAME: postgres
    env_file:
      - /api/.env
    ports:
      - 5000:5000

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3001:80
    links:
      -  api