const SET_ITEMS = "SET_ITEMS";
const SHOW_MODAL_VIEW = "SHOW_MODAL_VIEW";
const HIDE_MODAL_VIEW = "HIDE_MODAL_VIEW";
const SUBMIT_PHOTO = "SUBMIT_PHOTO";
const ISLOADING = "ISLOADING";

export default {
  SET_ITEMS,
  SHOW_MODAL_VIEW,
  HIDE_MODAL_VIEW,
  SUBMIT_PHOTO,
  ISLOADING,
};
